CREATE TABLE TOKEN_TRANSFERS
(
 seq            BIGINT NOT NULL,
 trx_seq        BIGINT NOT NULL,
 block_num      BIGINT NOT NULL,
 block_time     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
 trx_id         VARCHAR(64) NOT NULL,
 contract       VARCHAR(13) NOT NULL,
 currency       VARCHAR(8) NOT NULL,
 tx_from        VARCHAR(13) NOT NULL,
 tx_to          VARCHAR(13) NOT NULL,
 amount         DECIMAL(22,0) NOT NULL,
 memo           BYTEA NOT NULL
);


SELECT create_hypertable('TOKEN_TRANSFERS','block_time');

CREATE INDEX TOKEN_TRANSFERS_I01 ON TOKEN_TRANSFERS (seq);
CREATE INDEX TOKEN_TRANSFERS_I02 ON TOKEN_TRANSFERS (trx_seq);
CREATE INDEX TOKEN_TRANSFERS_I03 ON TOKEN_TRANSFERS (block_num);
CREATE INDEX TOKEN_TRANSFERS_I04 ON TOKEN_TRANSFERS (trx_id);
CREATE INDEX TOKEN_TRANSFERS_I05 ON TOKEN_TRANSFERS (contract, block_num);
CREATE INDEX TOKEN_TRANSFERS_I06 ON TOKEN_TRANSFERS (contract, seq);
CREATE INDEX TOKEN_TRANSFERS_I07 ON TOKEN_TRANSFERS (tx_from, block_num);
CREATE INDEX TOKEN_TRANSFERS_I08 ON TOKEN_TRANSFERS (tx_from, seq);
CREATE INDEX TOKEN_TRANSFERS_I09 ON TOKEN_TRANSFERS (tx_to, block_num);
CREATE INDEX TOKEN_TRANSFERS_I010 ON TOKEN_TRANSFERS (tx_to, seq);
